import React, { useState } from 'react';
import { Box, Container, Typography } from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';

const FAQS = [
  { q: 'How is the plan delivered?', a: 'After payment and completing the personalisation form, your plan is generated by AI and available for instant PDF download — usually within 2–5 minutes.' },
  { q: 'Is the plan really personalised?', a: 'Yes. Every plan is built from your specific inputs — body stats, goals, dietary preferences, equipment, and health history. No templates are used.' },
  { q: 'What if I am vegetarian or have food allergies?', a: 'All diet plans are fully customizable. You can specify vegetarian, eggetarian, or non-vegetarian preferences, and list any food allergies during the form.' },
  { q: 'Can I follow the workout at home?', a: 'Yes. You choose home or gym during the form, and your workout plan is designed around your available equipment.' },
  { q: 'What payment methods are accepted?', a: 'We accept all major payment methods via Razorpay — UPI, credit/debit cards, net banking, and wallets.' },
  { q: 'What is your refund policy?', a: 'We offer refunds within 7 days if you are not satisfied with your plan. Please contact us at dhanushkumar102@gmail.com with your order details.' },
  { q: 'How long is the plan valid?', a: 'Your plan is a one-time purchase with lifetime access to the PDF. You can re-download anytime from My Programs.' },
  { q: 'Can I buy multiple plans?', a: 'Yes. You can purchase any combination of plans, and each will appear separately in My Programs for download.' },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <Box
      onClick={() => setOpen(o => !o)}
      sx={{
        borderBottom: '1px solid #1A1A1A',
        py: 2.5, cursor: 'pointer',
        '&:last-child': { borderBottom: 'none' },
      }}
    >
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 2 }}>
        <Typography sx={{ fontSize: 15, fontWeight: 600, color: open ? '#fff' : '#C0C0C0', transition: 'color 0.2s' }}>
          {q}
        </Typography>
        <ExpandMoreIcon sx={{
          color: open ? '#FFD700' : '#555', flexShrink: 0, fontSize: 22,
          transition: 'transform 0.2s, color 0.2s',
          transform: open ? 'rotate(180deg)' : 'none',
        }} />
      </Box>
      {open && (
        <Typography sx={{ fontSize: 14, color: '#888', mt: 1.5, lineHeight: 1.7 }}>{a}</Typography>
      )}
    </Box>
  );
}

export default function FAQs() {
  return (
    <Box sx={{ bgcolor: '#000', minHeight: '100vh', pt: { xs: 10, md: 14 }, pb: { xs: 10, md: 16 } }}>
      <Container maxWidth="md">
        <Box sx={{ textAlign: 'center', mb: { xs: 6, md: 10 } }}>
          <Typography sx={{
            fontFamily: 'Montserrat,sans-serif', fontWeight: 900,
            fontSize: { xs: 28, md: 40 }, color: '#FFD700', letterSpacing: 2, mb: 1,
          }}>
            FAQs
          </Typography>
          <Typography sx={{ color: '#888', fontSize: 15 }}>
            Common questions about Xerxes programs and services.
          </Typography>
        </Box>

        <Box sx={{ bgcolor: '#111', border: '1px solid #1A1A1A', borderRadius: 3, px: { xs: 3, md: 5 }, py: 1 }}>
          {FAQS.map((faq, i) => <FAQItem key={i} q={faq.q} a={faq.a} />)}
        </Box>

        <Box sx={{ mt: 5, textAlign: 'center' }}>
          <Typography sx={{ color: '#555', fontSize: 14 }}>
            Still have questions?{' '}
            <Box component="a" href="mailto:dhanushkumar102@gmail.com" sx={{ color: '#FFD700', textDecoration: 'none', fontWeight: 700 }}>
              Email us
            </Box>
          </Typography>
        </Box>
      </Container>
    </Box>
  );
}
