import React from 'react';
import { Box, Container, Typography, Paper } from '@mui/material';

function Section({ title, children }) {
  return (
    <Box sx={{ mb: 4 }}>
      <Typography sx={{ fontFamily: 'Montserrat,sans-serif', fontWeight: 800, color: '#FFD700', fontSize: 16, mb: 1.5 }}>
        {title}
      </Typography>
      <Typography sx={{ color: '#888', fontSize: 14, lineHeight: 1.9 }}>{children}</Typography>
    </Box>
  );
}

export default function Terms() {
  return (
    <Box sx={{ bgcolor: '#000', minHeight: '100vh', pt: { xs: 10, md: 14 }, pb: { xs: 10, md: 16 } }}>
      <Container maxWidth="md">
        <Box sx={{ textAlign: 'center', mb: { xs: 6, md: 8 } }}>
          <Typography sx={{ fontFamily: 'Montserrat,sans-serif', fontWeight: 900, fontSize: { xs: 26, md: 36 }, color: '#FFD700', letterSpacing: 2, mb: 1 }}>
            Terms & Conditions
          </Typography>
          <Typography sx={{ color: '#555', fontSize: 13 }}>Last updated: January 2025</Typography>
        </Box>

        <Paper elevation={0} sx={{ bgcolor: '#111', border: '1px solid #222', borderRadius: 3, p: { xs: 3, sm: 5 } }}>
          <Section title="1. Acceptance of Terms">
            By accessing and using Xerxes Fitness services, you accept and agree to be bound by these Terms and Conditions. If you do not agree, please do not use our services.
          </Section>
          <Section title="2. Services">
            Xerxes Fitness provides AI-generated personalized fitness and diet plans for purchase. Plans are delivered as downloadable PDF files. All plans are generated specifically for the information you provide and are for personal use only.
          </Section>
          <Section title="3. Payment">
            All payments are processed securely via Razorpay. Prices are displayed in Indian Rupees (INR) and are inclusive of applicable taxes. Payment is required before plan generation begins.
          </Section>
          <Section title="4. Refund Policy">
            We offer refunds within 7 days of purchase if you are not satisfied with your plan. To request a refund, contact us at dhanushkumar102@gmail.com with your registered email and order details. Refunds are not provided for plans that have been downloaded more than once.
          </Section>
          <Section title="5. Health Disclaimer">
            The fitness and nutrition plans provided are for general informational purposes. Always consult a qualified healthcare provider before starting any new exercise or diet program, especially if you have pre-existing medical conditions. Xerxes Fitness is not liable for any health outcomes resulting from following the plans.
          </Section>
          <Section title="6. Intellectual Property">
            All plans, content, and materials generated by Xerxes Fitness are for personal use only. You may not resell, redistribute, or share the plans publicly without written consent.
          </Section>
          <Section title="7. Changes to Terms">
            We reserve the right to modify these terms at any time. Continued use of our services after changes constitutes acceptance of the updated terms.
          </Section>
          <Section title="8. Contact">
            For any questions regarding these terms, contact us at dhanushkumar102@gmail.com.
          </Section>
        </Paper>
      </Container>
    </Box>
  );
}
